export interface UploadedAsset {
  id: string;
  file: File;
  previewUrl: string;
  type: 'character' | 'scene' | 'element';
  description?: string; // Auto-generated by AI
}

export enum GridSize {
  Grid2x2 = 2,
  Grid3x3 = 3,
}

export enum AspectRatio {
  Square = "1:1",
  Standard = "4:3",
  Portrait = "3:4",
  Landscape = "16:9",
  Mobile = "9:16",
  Ultrawide = "21:9",
}

export enum ImageResolution {
  Res1K = "1K",
  Res2K = "2K",
  Res4K = "4K",
}

export interface GenerationSettings {
  gridSize: GridSize;
  aspectRatio: AspectRatio;
  resolution: ImageResolution;
  prompt: string;
}

export interface StoryboardFrame {
  id: string;
  imageUrl: string;
  index: number;
}

export interface StoryboardResult {
  originalImage: string; // The full grid image from API
  frames: StoryboardFrame[]; // Sliced images
  promptUsed: string;
}